### ISSUE TITLE
关于异步实现的一些问题

### ISSUE THREAD

**Issue by wangrunji0408** [HUST-OS/async-virtio-driver#1]
感谢你们的工作！

异步版本的 virtio 驱动我们之前一直想做来着，但是一直没有动手。
你们的工作是个很好的开始，期望完善后能够合并回 rCore 仓库里，为更多人所用。😀

我简单浏览了一下代码，发现一些问题想讨论一下：

### Future 与 waker 的实现

https://github.com/HUST-OS/async-virtio-driver/blob/824bb82f356c9e24313554ed4d5ca925684b5e6d/src/block.rs#L41-L46

按照 `Future::poll` 的实现规范，在返回 `Pending` 前一般需要将 waker 注册到某个 reactor，使得当事件发生时能够唤醒 Future。但是这里并没有注册 waker 的操作，所以我觉得是有问题的，会发生 Future 永远不被唤醒的情况（当然如果上层 executor 的实现不考虑 挂起-唤醒机制、即使返回 Pending 的任务也一直去 poll 就不会出现这种情况）。

我之前的经验是这种情况一般需要将 waker 保存到 Entry 中。waker 的大小是 2 个 usize，如果 Entry 空间足够大就可以直接放进去；如果不够的话，它至少会有一个 usize 的 user_data 变量，可以放 waker 的指针，此时 waker 就要用 Box 放到堆上或者 pin 在栈上以保证地址不变。这样异步请求的发起就实现了，接下来是异步响应的完成。一般需要实现一个 `poll_complete` 函数（类似现在的 `handle_interrupt`），遍历所有完成队列中的 Entry 并唤醒其中的 waker。此时 Entry 还不能被回收重用，因为接下来被唤醒的 Future 还需要去 Entry 里取结果，一般需要在 Future drop 时再释放回收 Entry。

### 平台相关代码的隔离

作为一个平台无关的驱动库，按说是不应该出现 riscv 平台特定代码的。这里的外部中断开关似乎也应该一直打开。不过具体涉及哪些实现上的问题我也还不清楚，之后可以看情况再做处理。

### &mut self

https://github.com/HUST-OS/async-virtio-driver/blob/824bb82f356c9e24313554ed4d5ca925684b5e6d/src/block.rs#L142

根据我之前的经验，这里应该用 `&self`。因为返回的 Future 会延续对 self 的引用。如果用 `&mut self` 的话会导致只能生成一个 Future，也就是任何时候只能有一个 IO 操作正在进行，这显然是退化回了同步 IO，无法发挥异步优势的。

### Send / Sync

https://github.com/HUST-OS/async-virtio-driver/blob/824bb82f356c9e24313554ed4d5ca925684b5e6d/src/block.rs#L52-L53

这个未来要仔细斟酌一下。我直觉上感觉它既不 Send 也不 Sync（但也不一定🤔）。

**Comment by SKTT1Ryze** [comment]
感谢学长的 issue！  
对于 `Future 与 waker` 实现的问题，其实该驱动库返回的 Future 会在操作系统内核里面被包装成一个任务，这个任务是我们异步运行时调度的基本单位：  

https://github.com/HUST-OS/tornado-os/blob/71d995a9a53c464c2573d876fe28df4287353d84/tornado-kernel/src/task/kernel_task.rs#L15-L24

而我们异步运行时中 executor 的实现是每次 poll 一个`任务`的时候去注册的 waker：  

https://github.com/HUST-OS/tornado-os/blob/71d995a9a53c464c2573d876fe28df4287353d84/tornado-kernel/src/task/executor.rs#L23-L25  

因此我们把注册 waker 的任务放到 executor 中做了，virtio 的外部中断来了之后会唤醒相应的`任务`，而不是 Future。  
这样做可能和我们的内核联系得比较紧密了，后面可能会考虑一下这里的兼容性设计，目前我们是想要一个可以运行的版本。  

关于`平台相关代码的隔离的问题`，这些开关中断的代码是我调试的时候为了减少干扰而加上的（当时遇到一个很神奇的 bug，调了比较长的时间），马上删掉这几行代码。  

关于 `&mut self` 的问题，这个也是我一直头疼的问题。我还不是很熟悉 Rust 异步模型中的写法，一开始写得时候被各种生命周期和所有权的问题困扰，代码无法通过。这里如果直接改为 &self  的话 async_read 方法体内就无法对 self 的成员做可变引用了。这里的代码后面是需要大改的，确实存在非常大的问题。  

关于 `Send/Sync` 的问题，这个也是后面我们需要解决的一个问题，目前这个驱动库还存在比较多的问题，需要进一步完善。  

这个项目大量参考了 rCore 社区，非常感谢！完善之后，一定合并回 rCore 社区。  
非常感谢学长的建议。
